### ISSUE TITLE
Simplified for syntax

### ISSUE THREAD

**Issue by JacksonKearl** [vrsperanza/CPY#1]
Can
`	for i = 0; i < size; i++
`
be replaced with 
`	for i size
`?
I notice the first version in a few places around the codebase and am not sure why it's not the second.

**Comment by vrsperanza** [comment]
This functionality was added in a later phase of the project, some examples were already in place, this is present is some examples to show it still works

**Comment by vrsperanza** [comment]
Changing it in the examples is easy, but I'm not sure it is a good idea, maybe some comments should be added?

**Comment by vrsperanza** [comment]
It surely can, and it was.
Thanks for the heads up, those examples were made in a time when that functionality did not exist.
