### ISSUE TITLE
ArchLinux: Segfaults at `--help`

### ISSUE THREAD

**Issue by xyproto** [vrsperanza/CPY#10]
Hi,

I just created the [AUR package](https://aur.archlinux.org/packages/cpy/) for CPY.

When given the `--help` parameter, `cpy` segfaults here:

    cpy --help
    zsh: segmentation fault (core dumped)  cpy --help

I know `--help` is not on the list of supported options, but expected behavior is to output a list of supported options instead of segfaulting.

I'm on 64-bit Arch Linux using GCC 8.1.0.

**Comment by vrsperanza** [comment]
This program's flags are meant to be used preceded by a single '-'.
Either way I failed to reproduce the segfault, this is no doubt a portability issue.
Here "cpy -h" and "cpy -help" both work fine. "-help" is not on the list of supported options but it is supposed to be an alternative to "-h".

Do you think it would be a good idea to add support for a second '-' preceding flags?

**Comment by vrsperanza** [comment]
Issue fixed
