### ISSUE TITLE
ArchLinux: Unable to compile code

### ISSUE THREAD

**Issue by xyproto** [vrsperanza/CPY#11]
Hi,

When entering the `Simple sum` directory and entering `cpy main.cpy`, I get the following output:

    g++ -c main.cpp -o main.o
    g++ -o ../a main.o

But `../a` is nowhere to be found:

    ls ../a
    ls: cannot access '../a': No such file or directory.

Trying to run the sample code with `-r` did not give any results here either:

    cpy -r main.cpy
    g++ -o ../a main.o
    Running code:
    sh: ../a: No such file or directory

How are the samples meant to be run? I could not find any documentation for this.

**Comment by xyproto** [comment]
I'm on 64-bit Arch Linux using GCC 8.1.0.

**Comment by vrsperanza** [comment]
It compiles code inside the "compilationSource" folder, the line "g++ -o ../a main.o" links the object files and moves the executable to your project's root folder.
In this case, after running "cpy main.cpy", the command "./a" should sucessfully run the code.

I could not reproduce this problem with -r, will try again in another linux build today (probably)

**Comment by vrsperanza** [comment]
I managed to reproduce the issue in archlinux and only in archlinux.
I honestly have no idea as to what's it's cause and will only be able to fully address it in a few days, in the meantime if you discover something, please let me know

**Comment by okayzed** [comment]
I looked into this, and I believe that the line in main.cpp:

`compilation += "-o " + trueTarget + " ";`

should be

`compilation += "-o " + target + " "; `

because later on the following is done:

```
		remove(trueTarget.c_str());
		rename(target.c_str(), trueTarget.c_str());
```

**Comment by vrsperanza** [comment]
Thank you okayzed
Issue should now be fixed
