### ISSUE TITLE
Import external headers

### ISSUE THREAD

**Issue by TheSalarKhan** [vrsperanza/CPY#2]
Hi!
First of all.... what you've done here is just heroic!! <3 I love this project.. Just wanted to ask, is there a way we can include external headers and stuff? Like is there a syntax to do that?

**Comment by vrsperanza** [comment]
Sorry, I didn't understand what you want, could you give me a pratical
example of it done in standard C++?
If there's a way to do it in C++ there should be a way to do it in CPY.
If there currently isn't, I (or we if you want) must make it happen

Em sáb, 5 de mai de 2018 18:11, Muhammad Salar Khan <
notifications@github.com> escreveu:

**Comment by vrsperanza** [comment]
If assent.h is a standard library you can include it with
#include <assert.h>
Just as in C++
If it is a file you wrote, that is available in the same folder or a child
folder of the current folder, you can include it with
#include "assert.h"
I tryed my best to make the code in a way that if something is not
understood by the cpy compiler, it behaves exactly as it would in c++
Suposedly if you rename a .cpp file to .cpy, cpy would compile it without
any problem, so if something is not available in cpy and you still want to
use it, you can code it as you would in c++ and it will compile

Em sáb, 5 de mai de 2018 20:23, Muhammad Salar Khan <
notifications@github.com> escreveu:

**Comment by TheSalarKhan** [comment]
That's just awesome man! Keep up the good work. I'll try this out soon. Thanks! 👍
