### ISSUE TITLE
Problem with comments

### ISSUE THREAD

**Issue by stasoid** [vrsperanza/CPY#7]
File `hello.cpy` with this content:
```
#include <stdio.h>
/*(*/
int main(){puts("hello");}
```
CPY enters infinite loop while compiling it, in `replaceQuickPrints()`. This is because it tries to process contents of comment.
I want to create pull request that removes comments during processing.
Is it acceptable solution for you?

**Comment by vrsperanza** [comment]
It is a valid solution, although I'd prefer to avoid it
If you do it I'll gladly merge it, at elast as an optional flag

Once I have time I'll try to solve this problem. I probably forgot to treat
comments inside firstReplaces

Em qui, 10 de mai de 2018 08:07, stasoid <notifications@github.com>
escreveu:
