### ISSUE TITLE
Adding colon to enhance readability

### ISSUE THREAD

**Issue by battaglia01** [vrsperanza/CPY#9]
Great project, had a suggestion to clear up ambiguity. Have you considered adding an option for the parser to read a colon, similar to Python, to make indented code segments easier to read? for instance

```
myFunction()
   myFunction2()
```

would become

```
myFunction():
   myFunction2()
```

which makes it more obvious that we're starting a function definition.

If you would approve this I might do a PR when I get the time...

**Comment by vrsperanza** [comment]
I would aprove making this optional but not mandatory, I see no problem in adding a pre-processing step that removes all ':' in declarations and then proceeds to do the rest of the compilation process.
I would also aprove it if it was mandatory, but only as a separate flag (and option in an eventual config file)

**Comment by vrsperanza** [comment]
The ambiguity you are referring to is exclusively visual, human ambiguity, right?
Or am I missing something?

**Comment by battaglia01** [comment]
Yeah, it's just for ease of readability. I'm not sure if it's really necessary from syntactic standpoint.

**Comment by vrsperanza** [comment]
Then my first comment stands true

**Comment by battaglia01** [comment]
Actually, I think this is needed if you ever have syntax on one line.

Look at `if x - y < z, blah()` - with the comma deliberately in there. That could be both of these:

```
if x
    -y < z, blah()
```

```
if x - y < z
    , blah()
```
How do you know which is which?
